version: "3.8"  # Updated for better network support

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
       - .:/usr/src/app
       - /usr/src/app/__pycache__